// data structure of blood donors
const bloodDonors = [
  {
    id: 1,
    name: "Md. Shafikul Islam",
    age: 24,
    gender: "Male",
    blood_group: "O+",
    location: "Narsingdi",
    cell: "01777883351",
    last_donate: 130,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Sharif", donation_date: "2-6-21" },
    ],
  },
  {
    id: 2,
    name: "Mizanur Rahman",
    age: 32,
    gender: "Male",
    blood_group: "B+",
    location: "Chittagong",
    cell: "01777883352",
    last_donate: 160,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Forid", donation_date: "2-6-21" },
      { donated_to: "Masud", donation_date: "2-8-20" },
    ],
  },
  {
    id: 3,
    name: "Abdul Rahman",
    age: 34,
    gender: "Male",
    blood_group: "AB-",
    location: "Rajshahi",
    cell: "01777883353",
    last_donate: 115,
    donation: [
      { donated_to: "Shakib", donation_date: "2-3-23" },
      { donated_to: "Apon", donation_date: "5-3-22" },
      { donated_to: "Ashik", donation_date: "2-6-21" },
    ],
  },
  {
    id: 4,
    name: "Fatima Begum",
    age: 27,
    gender: "Female",
    blood_group: "O+",
    location: "Khulna",
    cell: "01777883354",
    last_donate: 80,
    donation: [{ donated_to: "Shimul", donation_date: "2-3-23" }],
  },
  {
    id: 5,
    name: "Ali Hasan",
    age: 31,
    gender: "Male",
    blood_group: "A-",
    location: "Sylhet",
    cell: "01777883355",
    last_donate: 20,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Rashed", donation_date: "5-3-22" },
      { donated_to: "Forid", donation_date: "2-6-21" },
    ],
  },
  {
    id: 6,
    name: "Nusrat Jahan",
    age: 26,
    gender: "Female",
    blood_group: "B-",
    location: "Dhaka",
    cell: "01912345671",
    last_donate: 100,
    donation: [
      { donated_to: "Rohan", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Hridoy", donation_date: "2-6-21" },
    ],
  },
  {
    id: 7,
    name: "Ahmed Ali",
    age: 29,
    gender: "Male",
    blood_group: "O-",
    location: "Chittagong",
    cell: "01712345672",
    last_donate: 58,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Morad", donation_date: "2-6-21" },
      { donated_to: "Polash", donation_date: "2-6-20" },
    ],
  },
  {
    id: 8,
    name: "Fahmida Aktar",
    age: 35,
    gender: "Female",
    blood_group: "A+",
    location: "Rajshahi",
    cell: "01812345673",
    last_donate: 180,
    donation: [
      { donated_to: "Alom", donation_date: "2-3-23" },
      { donated_to: "Runa", donation_date: "5-3-22" },
      { donated_to: "Mousome", donation_date: "2-6-21" },
    ],
  },
  {
    id: 9,
    name: "Kamrul Hasan",
    age: 32,
    gender: "Male",
    blood_group: "AB+",
    location: "Khulna",
    cell: "01912345674",
    last_donate: 135,
    donation: [
      { donated_to: "Kawsar", donation_date: "2-3-23" },
      { donated_to: "Jahangir", donation_date: "5-3-22" },
      { donated_to: "Arman", donation_date: "2-6-21" },
    ],
  },
  {
    id: 10,
    name: "Farhana Rahman",
    age: 27,
    gender: "Female",
    blood_group: "B+",
    location: "Sylhet",
    cell: "01712345675",
    last_donate: 150,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Nazmul", donation_date: "2-6-21" },
    ],
  },
  {
    id: 11,
    name: "Abdul Malek",
    age: 30,
    gender: "Male",
    blood_group: "O+",
    location: "Dhaka",
    cell: "01812345676",
    last_donate: 5,
    donation: [
      { donated_to: "Dipty", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
    ],
  },
  {
    id: 12,
    name: "Fatima Akhter",
    age: 29,
    gender: "Female",
    blood_group: "A-",
    location: "Chittagong",
    cell: "01912345677",
    last_donate: 200,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Nilanjona", donation_date: "5-3-22" },
      { donated_to: "Fardin", donation_date: "2-6-21" },
    ],
  },
  {
    id: 13,
    name: "Mohammed Khan",
    age: 33,
    gender: "Male",
    blood_group: "AB-",
    location: "Rajshahi",
    cell: "01712345688",
    last_donate: 100,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Raduan", donation_date: "2-6-21" },
    ],
  },
  {
    id: 14,
    name: "Sadia Ahmed",
    age: 28,
    gender: "Female",
    blood_group: "O-",
    location: "Khulna",
    cell: "01812345679",
    last_donate: 110,
    donation: [{ donated_to: "Mizanur Rahman", donation_date: "2-6-21" }],
  },
  {
    id: 15,
    name: "Shamim Aktar",
    age: 31,
    gender: "Female",
    blood_group: "A+",
    location: "Sylhet",
    cell: "01912345000",
    last_donate: 110,
    donation: [{ donated_to: "Neela", donation_date: "5-3-22" }],
  },
  {
    id: 16,
    name: "Nadia Sultana",
    age: 28,
    gender: "Female",
    blood_group: "B-",
    location: "Dhaka",
    cell: "01712345222",
    last_donate: 140,
    donation: [
      { donated_to: "Afrose", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Forid", donation_date: "2-6-21" },
    ],
  },
  {
    id: 17,
    name: "Azizur Rahman",
    age: 34,
    gender: "Male",
    blood_group: "AB+",
    location: "Chittagong",
    cell: "01812345601",
    last_donate: 130,
    donation: [
      { donated_to: "Rohima", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Tripti", donation_date: "2-6-21" },
    ],
  },
  {
    id: 18,
    name: "Sultana Begum",
    age: 29,
    gender: "Female",
    blood_group: "O+",
    location: "Rajshahi",
    cell: "01912345600",
    last_donate: 135,
    donation: [
      { donated_to: "Susmita", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Jahirul Islam", donation_date: "2-6-21" },
    ],
  },
  {
    id: 19,
    name: "Kamal Hasan",
    age: 32,
    gender: "Male",
    blood_group: "B+",
    location: "Khulna",
    cell: "01712345633",
    last_donate: 110,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Forid", donation_date: "2-6-21" },
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Nurul Islam", donation_date: "2-6-21" },
    ],
  },
  {
    id: 20,
    name: "Rahima Khan",
    age: 31,
    gender: "Female",
    blood_group: "O-",
    location: "Sylhet",
    cell: "01812345111",
    last_donate: 188,
    donation: [
      { donated_to: "Sumaiya", donation_date: "2-3-23" },
      { donated_to: "Neela", donation_date: "5-3-22" },
      { donated_to: "Priya", donation_date: "2-6-21" },
    ],
  },
]; //data structure ends here

